trigger:
  - master

variables:
  GIT_COMMITTER_NAME: "ghp-import-bot"
  GIT_COMMITTER_EMAIL: "ghp@import.bot"

strategy:
  matrix:
    macos:
      vmImage: macos
    windows:
      vmImage: windows

pool:
  vmImage: $(vmImage)-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: "Setting up Python"

  - pwsh: git remote add github "https://$(GITHUB_TOKEN)@github.com/c-w/ghp-import.git" 2>&1 | Out-Null
    displayName: "Setting up git remote"

  - pwsh: make install
    displayName: "Installing dependencies"

  - pwsh: make -e DOCS_BRANCH="test-azuredevops-$(vmImage)-$(Build.BuildNumber)" -e DOCS_REMOTE=github docs clean
    displayName: "Running integration tests"
